/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tournamentmanager.view;

import com.sun.glass.events.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import tournamentmanager.database.LoginManager;
import tournamentmanager.entities.Admin;

/**
 *
 * @author Jacinto López Hernández
 */
public class MainView extends javax.swing.JFrame {

    public static tournamentmanager.database.MySQLConnector mySqlConnector;

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        initConnection();
        initLoginDialog();
        this.setLocationRelativeTo(null);
    }

    /**
     * initializes the login form dialog
     */
    private void initLoginDialog() {
        jDialogLogin.setLocationRelativeTo(this);
        jDialogLogin.requestFocusInWindow();
        jDialogLogin.setVisible(true);
    }

    /**
     * initializes the MySQL connection
     */
    private void initConnection() {
        mySqlConnector = tournamentmanager.database.ConnectionWrapper.initConnection();
    }

    /**
     * Sets the Look And Feel of the application to the one selected by the user
     * @param index theme
     */
    private void setTheme(int index) {
        LookAndFeel laf = UIManager.getLookAndFeel();

        switch (index) {
            case 0:
                laf = new com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme();
                break;
            case 1:
                laf = new com.formdev.flatlaf.intellijthemes.FlatArcDarkOrangeIJTheme();
                break;
            case 2:
                laf = new com.formdev.flatlaf.intellijthemes.FlatGradiantoNatureGreenIJTheme();
                break;
            case 3:
                laf = new com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatGitHubIJTheme();
                break;
            case 4:
                laf = new com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatGitHubDarkIJTheme();
                break;
        }
        try {
            UIManager.setLookAndFeel(laf);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
        SwingUtilities.updateComponentTreeUI(this);
        SwingUtilities.updateComponentTreeUI(jDialogHelp);
        SwingUtilities.updateComponentTreeUI(jDialogSettings);
        SwingUtilities.updateComponentTreeUI(jDialogVersion);
        SwingUtilities.updateComponentTreeUI(jDialogLogin);
    }
    
    /**
     * Closes the application
     */
    public void closeApplication() {
        mySqlConnector.cnxClose();
        System.exit(0);
    }

    /**
     * Logins into the application
     */
    public void login() {
        if (isInputEmpty(jTextFieldPwd) | isInputEmpty(jTextFieldLogin)) {
            jLabelErrorLogin.setText("Input fields not filled properly");
        } else {
            String user = jTextFieldLogin.getText();
            String pwd = jTextFieldPwd.getText();
            Admin admin = new Admin(user, pwd);
            String output = LoginManager.checkLogin(admin);
            jLabelErrorLogin.setText(output);
            this.setLocationRelativeTo(null);
            this.setVisible(true);
            this.requestFocusInWindow();
            jDialogLogin.setVisible(false);
        }
    }

    /**
     * Checks wether the input field is empty or not
     *
     * @param jtxt
     * @return true - if it's empty, false otherwise
     */
    private boolean isInputEmpty(JTextField jtxt) {
        if (jtxt.getText().equals("")) {
            jtxt.setBackground(new java.awt.Color(156, 56, 35));
            jtxt.putClientProperty("JComponent.outline", "error");
            jLabelErrorLogin.setText("Input fields not filled properly");
            return true;
        }
        jtxt.setBackground(UIManager.getLookAndFeelDefaults().getColor(jtxt));
        return false;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogLogin = new javax.swing.JDialog();
        jLabelLoginTitle = new javax.swing.JLabel();
        jLabelLoginUser = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jTextFieldPwd = new javax.swing.JTextField();
        jLabelLoginPassword = new javax.swing.JLabel();
        jButtonConnect = new javax.swing.JButton();
        jButtonDialogClose = new javax.swing.JButton();
        jLabelErrorLogin = new javax.swing.JLabel();
        jDialogHelp = new javax.swing.JDialog();
        jLabelHelpLabel = new javax.swing.JLabel();
        jButtonHelpOk = new javax.swing.JButton();
        jDialogVersion = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jButtonOkVersion = new javax.swing.JButton();
        jDialogSettings = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxThemes = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButtonSettingsExit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TournamentTable = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonNewTourney = new javax.swing.JButton();
        jButtonLoadTourney = new javax.swing.JButton();
        jButtonEditTourney = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemNew = new javax.swing.JMenuItem();
        jMenuItemLoad = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuItemAddPlayer = new javax.swing.JMenuItem();
        jMenuItemAddRound = new javax.swing.JMenuItem();
        jMenuTools = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuAbout = new javax.swing.JMenu();
        jMenuItemHelp = new javax.swing.JMenuItem();
        jMenuItemVersion = new javax.swing.JMenuItem();

        jDialogLogin.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialogLogin.setTitle("LOGIN");
        jDialogLogin.setModal(true);
        jDialogLogin.setResizable(false);
        jDialogLogin.setSize(new java.awt.Dimension(294, 245));
        jDialogLogin.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                jDialogLoginWindowClosed(evt);
            }
        });

        jLabelLoginTitle.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabelLoginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLoginTitle.setText("LOGIN");
        jLabelLoginTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelLoginUser.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabelLoginUser.setText("User");

        jTextFieldLogin.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jTextFieldLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldLoginKeyPressed(evt);
            }
        });

        jTextFieldPwd.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jTextFieldPwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldLoginKeyPressed(evt);
            }
        });

        jLabelLoginPassword.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabelLoginPassword.setText("Password");

        jButtonConnect.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jButtonConnect.setText("Connect");
        jButtonConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnectActionPerformed(evt);
            }
        });

        jButtonDialogClose.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jButtonDialogClose.setText("Exit");
        jButtonDialogClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDialogCloseActionPerformed(evt);
            }
        });

        jLabelErrorLogin.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabelErrorLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelErrorLogin.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jDialogLoginLayout = new javax.swing.GroupLayout(jDialogLogin.getContentPane());
        jDialogLogin.getContentPane().setLayout(jDialogLoginLayout);
        jDialogLoginLayout.setHorizontalGroup(
            jDialogLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLoginTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDialogLoginLayout.createSequentialGroup()
                        .addGroup(jDialogLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelLoginUser)
                            .addComponent(jLabelLoginPassword))
                        .addGap(18, 18, 18)
                        .addGroup(jDialogLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldPwd, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(jTextFieldLogin))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogLoginLayout.createSequentialGroup()
                        .addComponent(jButtonConnect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDialogClose, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelErrorLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDialogLoginLayout.setVerticalGroup(
            jDialogLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDialogLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLoginUser)
                    .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLoginPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelErrorLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDialogLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConnect)
                    .addComponent(jButtonDialogClose))
                .addContainerGap())
        );

        jDialogHelp.setTitle("HELP");
        jDialogHelp.setModal(true);
        jDialogHelp.setPreferredSize(new java.awt.Dimension(246, 180));
        jDialogHelp.setResizable(false);
        jDialogHelp.setSize(new java.awt.Dimension(246, 180));

        jLabelHelpLabel.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabelHelpLabel.setText("<html>This application was built by <br/><b> Jacinto López Hernández </b><br/><br/>\nFor further information<br/> <a href=\"mailto:jacilopezwork@gmail.com\">jacilopezwork@gmail.com</a><br/></html>");
        jLabelHelpLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jButtonHelpOk.setText("OK");
        jButtonHelpOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHelpOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogHelpLayout = new javax.swing.GroupLayout(jDialogHelp.getContentPane());
        jDialogHelp.getContentPane().setLayout(jDialogHelpLayout);
        jDialogHelpLayout.setHorizontalGroup(
            jDialogHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHelpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(jButtonHelpOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDialogHelpLayout.setVerticalGroup(
            jDialogHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHelpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonHelpOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDialogVersion.setTitle("VERSION");
        jDialogVersion.setModal(true);
        jDialogVersion.setPreferredSize(new java.awt.Dimension(221, 149));
        jDialogVersion.setResizable(false);
        jDialogVersion.setSize(new java.awt.Dimension(221, 149));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Version : 1.00");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jButtonOkVersion.setText("Ok");
        jButtonOkVersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkVersionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogVersionLayout = new javax.swing.GroupLayout(jDialogVersion.getContentPane());
        jDialogVersion.getContentPane().setLayout(jDialogVersionLayout);
        jDialogVersionLayout.setHorizontalGroup(
            jDialogVersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogVersionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogVersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(jButtonOkVersion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDialogVersionLayout.setVerticalGroup(
            jDialogVersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogVersionLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jButtonOkVersion)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jDialogSettings.setTitle("SETTINGS");
        jDialogSettings.setPreferredSize(new java.awt.Dimension(400, 350));
        jDialogSettings.setResizable(false);
        jDialogSettings.setSize(new java.awt.Dimension(400, 350));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel4.setText("Theme");

        jComboBoxThemes.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jComboBoxThemes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arc Orange", "Arc Dark Orange", "Nature Green", "GitHub", "GitHub dark" }));
        jComboBoxThemes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxThemesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxThemes, 0, 280, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxThemes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SETTINGS");

        jButtonSettingsExit.setText("Exit");
        jButtonSettingsExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSettingsExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogSettingsLayout = new javax.swing.GroupLayout(jDialogSettings.getContentPane());
        jDialogSettings.getContentPane().setLayout(jDialogSettingsLayout);
        jDialogSettingsLayout.setHorizontalGroup(
            jDialogSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogSettingsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSettingsExit)))
                .addContainerGap())
        );
        jDialogSettingsLayout.setVerticalGroup(
            jDialogSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSettingsExit)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tournament Manager");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 939, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TournamentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TournamentTable);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButtonNewTourney.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jButtonNewTourney.setText("New...");
        jButtonNewTourney.setToolTipText("Create a new tournament");
        jButtonNewTourney.setFocusable(false);
        jButtonNewTourney.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNewTourney.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonNewTourney);

        jButtonLoadTourney.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jButtonLoadTourney.setText("Load...");
        jButtonLoadTourney.setToolTipText("Load an previous tournament");
        jButtonLoadTourney.setFocusable(false);
        jButtonLoadTourney.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonLoadTourney.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonLoadTourney);

        jButtonEditTourney.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jButtonEditTourney.setText("Edit...");
        jButtonEditTourney.setToolTipText("Edit tournament");
        jButtonEditTourney.setFocusable(false);
        jButtonEditTourney.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEditTourney.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonEditTourney);

        jButton4.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);

        jButtonClose.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jButtonClose.setText("Exit");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Placeholder");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenuFile.setText("File");
        jMenuFile.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N

        jMenuItemNew.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jMenuItemNew.setText("New...");
        jMenuFile.add(jMenuItemNew);

        jMenuItemLoad.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jMenuItemLoad.setText("Load...");
        jMenuFile.add(jMenuItemLoad);

        jMenuItemExit.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar1.add(jMenuFile);

        jMenuEdit.setText("Edit");
        jMenuEdit.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N

        jMenuItemAddPlayer.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jMenuItemAddPlayer.setText("Add Player...");
        jMenuItemAddPlayer.setToolTipText("");
        jMenuEdit.add(jMenuItemAddPlayer);

        jMenuItemAddRound.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jMenuItemAddRound.setText("Add Round...");
        jMenuEdit.add(jMenuItemAddRound);

        jMenuBar1.add(jMenuEdit);

        jMenuTools.setText("Tools");
        jMenuTools.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jMenuItem1.setText("Settings");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuTools.add(jMenuItem1);

        jMenuBar1.add(jMenuTools);

        jMenuAbout.setText("About");
        jMenuAbout.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N

        jMenuItemHelp.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jMenuItemHelp.setText("Help");
        jMenuItemHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHelpActionPerformed(evt);
            }
        });
        jMenuAbout.add(jMenuItemHelp);

        jMenuItemVersion.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jMenuItemVersion.setText("Version");
        jMenuItemVersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVersionActionPerformed(evt);
            }
        });
        jMenuAbout.add(jMenuItemVersion);

        jMenuBar1.add(jMenuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        closeApplication();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        closeApplication();
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    

    private void jButtonConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnectActionPerformed
        login();
    }//GEN-LAST:event_jButtonConnectActionPerformed

    private void jButtonDialogCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDialogCloseActionPerformed
        jDialogLogin.dispose();
        closeApplication();
    }//GEN-LAST:event_jButtonDialogCloseActionPerformed

    private void jDialogLoginWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogLoginWindowClosed
        closeApplication();
    }//GEN-LAST:event_jDialogLoginWindowClosed

    private void jTextFieldLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLoginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login();
        }
    }//GEN-LAST:event_jTextFieldLoginKeyPressed

    private void jButtonHelpOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHelpOkActionPerformed
        jDialogHelp.dispose();
    }//GEN-LAST:event_jButtonHelpOkActionPerformed

    private void jMenuItemHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHelpActionPerformed
        jDialogHelp.setLocationRelativeTo(null);
        jDialogHelp.setVisible(true);
    }//GEN-LAST:event_jMenuItemHelpActionPerformed

    private void jMenuItemVersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVersionActionPerformed
        jDialogVersion.setLocationRelativeTo(null);
        jDialogVersion.setVisible(true);
    }//GEN-LAST:event_jMenuItemVersionActionPerformed

    private void jButtonOkVersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkVersionActionPerformed
        jDialogVersion.dispose();
    }//GEN-LAST:event_jButtonOkVersionActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jDialogSettings.setLocationRelativeTo(null);
        jDialogSettings.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButtonSettingsExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSettingsExitActionPerformed
        jDialogSettings.dispose();
    }//GEN-LAST:event_jButtonSettingsExitActionPerformed

    private void jComboBoxThemesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxThemesActionPerformed
        int theme_index = jComboBoxThemes.getSelectedIndex();
        setTheme(theme_index);
    }//GEN-LAST:event_jComboBoxThemesActionPerformed

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new com.formdev.flatlaf.intellijthemes.FlatGradiantoNatureGreenIJTheme());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TournamentTable;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonConnect;
    private javax.swing.JButton jButtonDialogClose;
    private javax.swing.JButton jButtonEditTourney;
    private javax.swing.JButton jButtonHelpOk;
    private javax.swing.JButton jButtonLoadTourney;
    private javax.swing.JButton jButtonNewTourney;
    private javax.swing.JButton jButtonOkVersion;
    private javax.swing.JButton jButtonSettingsExit;
    private javax.swing.JComboBox<String> jComboBoxThemes;
    private javax.swing.JDialog jDialogHelp;
    private javax.swing.JDialog jDialogLogin;
    private javax.swing.JDialog jDialogSettings;
    private javax.swing.JDialog jDialogVersion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelErrorLogin;
    private javax.swing.JLabel jLabelHelpLabel;
    private javax.swing.JLabel jLabelLoginPassword;
    private javax.swing.JLabel jLabelLoginTitle;
    private javax.swing.JLabel jLabelLoginUser;
    private javax.swing.JMenu jMenuAbout;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAddPlayer;
    private javax.swing.JMenuItem jMenuItemAddRound;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemHelp;
    private javax.swing.JMenuItem jMenuItemLoad;
    private javax.swing.JMenuItem jMenuItemNew;
    private javax.swing.JMenuItem jMenuItemVersion;
    private javax.swing.JMenu jMenuTools;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldPwd;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
